name: Update Blocklists and Format for AdGuard

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  update-blocklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download raw lists
        run: |
          mkdir -p rawlists
          curl -L https://raw.githubusercontent.com/joeylane/osint-blocklist/main/osint-trackers.txt -o rawlists/osint-trackers-raw.txt
          curl -L https://raw.githubusercontent.com/joeylane/osint-blocklist/main/osint-tracking.txt -o rawlists/osint-tracking-raw.txt
          curl -L https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dns/threat-intelligence/ti-default.list -o rawlists/hagezi-ti-raw.txt

      - name: Format lists for AdGuard
        run: |
          format_list() {
            local input_file=$1
            local output_file=$2
            local title=$3
            local description=$4

            echo "[Adblock Plus]" > $output_file
            echo "! Title: $title" >> $output_file
            echo "! Description: $description" >> $output_file
            echo "! Homepage: https://github.com/equivisync/network-data" >> $output_file
            echo "! Expires: 1 day" >> $output_file
            echo "! Last modified: $(date -u +"%d %b %Y %H:%M UTC")" >> $output_file
            echo "! Syntax: Adblock" >> $output_file
            echo "! Number of entries: auto" >> $output_file
            echo "!" >> $output_file

            grep -ve '^#\|^$\|^!' "$input_file" \
            | awk '{print $1}' \
            | grep -Eo '([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}' \
            | sort -u \
            | sed 's/^/||/; s/$/^/' >> "$output_file"
          }

          format_list rawlists/osint-trackers-raw.txt osint-trackers-tb.txt "OSINT Trackers Blocklist" "Domains from the OSINT Trackers list"
          format_list rawlists/osint-tracking-raw.txt osint-tb.txt "OSINT Tracking Blocklist" "Domains from the OSINT Tracking list"
          format_list rawlists/hagezi-ti-raw.txt hagezi-ti-tb.txt "HaGeZi Threat Intelligence Default Blocklist" "Domains from HaGeZi TI Default list"

      - name: Commit and push updates
        run: |
          git config --global user.name "Ghost Updater"
          git config --global user.email "ghost@nowhere.local"
          git add *.txt
          git commit -m "Daily blocklist auto-update"
          git push
