name: Update Blocklists and Format for AdGuard

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  update-blocklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download raw lists
        run: |
          mkdir -p rawlists
          curl -L https://raw.githubusercontent.com/0xERR0R/blocklist/main/hosts.txt -o rawlists/0xerr-raw.txt
          curl -L https://raw.githubusercontent.com/lightswitch05/hosts/master/tracking-aggressive.list -o rawlists/lightswitch05-raw.txt
          curl -L https://raw.githubusercontent.com/joeylane/osint-blocklist/main/osint-trackers.list -o rawlists/osint-raw.txt
          curl -L https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dns/threat-intelligence/default.txt -o rawlists/hagezi-ti-raw.txt

      - name: Format lists for AdGuard
        run: |
          for file in rawlists/*.txt; do
            base=$(basename "$file" -raw.txt)
            output="${base}-tb.txt"
            echo "[Adblock Plus]" > "$output"
            echo "! Title: $base (TB Ver)" >> "$output"
            echo "! Description: Converted for AdGuard use." >> "$output"
            echo "! Expires: 1 day" >> "$output"
            echo "! Last modified: $(date -u +"%d %b %Y %H:%M UTC")" >> "$output"
            echo "! Syntax: Adblock" >> "$output"
            echo "!" >> "$output"
            grep -vE '^(!|#|\[|$)' "$file" | grep -Eo '([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})' | sort -u | sed 's/^/||/' | sed 's/$/\^/' >> "$output"
          done

      - name: Commit and push updates
        run: |
          git config --global user.name "Ghost Updater"
          git config --global user.email "ghost@nowhere.local"
          git add *.txt
          git commit -m "Daily blocklist auto-update"
          git push
